version: '2'
services:
  # php:
  #   image: yiisoftware/yii2-php:7.4-apache
  #   volumes:
  #     - ~/.composer-docker/cache:/root/.composer/cache:delegated
  #     - ./:/app:delegated
  #   ports:
  #     - '8000:80'

  db:
    image: library/mariadb:10.5.8
    restart: always
    container_name: ${CONTAINER_NAME_PREFIX}-db
    ports:
     - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql/
